name: SonarCloud Scan

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Set up JDK
#        uses: actions/setup-java@v2
#        with:
#          java-version: '11'

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 17
          cache: "maven" # enable caching for Maven dependencies

      - name: Build with Maven
        run: mvn clean install -B -U

      - name: Run SonarCloud analysis
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=billsam -Dsonar.organization=Piga Hacks -Dsonar.host.url=https://sonarcloud.io